  version: '3.7'

  services:
    app:
      build:
        context: .
      volumes:
        - ./polr:/var/www/polr
      depends_on:
        - db
      networks:
        - frontend-network

    web:
      image: nginx:latest
      volumes:
        - ./polr:/var/www/polr
        - ./polr-nginx.conf:/etc/nginx/conf.d/default.conf
      expose:
        - 80
      depends_on:
        - app
      networks:
        - frontend-network
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.polr.rule=Host(`url-short.fnx.tools`)"
        - "traefik.http.routers.polr.entrypoints=web"
        - "traefik.http.services.polr.loadbalancer.server.port=80"

    db:
      image: mariadb:10.5
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: polrdb
        MYSQL_USER: polruser
        MYSQL_PASSWORD: polrpassword
      volumes:
        - /fenix/url_short/db_data:/var/lib/mysql
      networks:
        - frontend-network

  networks:
    frontend-network:
      external : true

  volumes:
    db_data:
